services:
  - type: web
    name: running-poster-generator
    env: static
    staticPublishPath: frontend/
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
